# Generated by Django 3.2.16 on 2022-11-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course', models.CharField(max_length=25)),
                ('fee', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
    ]
