# Generated by Django 3.2.16 on 2022-11-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('s_id', models.AutoField(db_column='s-id', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('e_mail', models.CharField(db_column='e-mail', max_length=50)),
                ('gender', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'register',
                'managed': False,
            },
        ),
    ]
